USE ROLE SYSADMIN;


CREATE OR REPLACE DATABASE PSX_DB;

CREATE OR REPLACE SCHEMA PSX_DB.RAW;
CREATE OR REPLACE SCHEMA PSX_DB.STAGING;
CREATE OR REPLACE SCHEMA PSX_DB.DWH;

CREATE OR REPLACE WAREHOUSE PROJECT_WH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

    

