SELECT
  *
FROM
  "PSX_DB"."RAW"."PSX_DATA"
LIMIT
  10;

  CREATE OR REPLACE TABLE PSX_DB.STAGING.STG_PSX_DATA AS
SELECT DISTINCT
    TO_DATE(Date) AS TRADE_DATE,
    Symbol AS STOCK_SYMBOL,
    Open AS OPEN_PRICE,
    High AS HIGH_PRICE,
    Low AS LOW_PRICE,
    Close AS CLOSE_PRICE
FROM PSX_DB.RAW.PSX_DATA;


