CREATE OR REPLACE TABLE PSX_DB.DWH.DIM_STOCK AS
SELECT DISTINCT
    STOCK_SYMBOL,
    INITCAP(STOCK_SYMBOL) AS STOCK_NAME
FROM PSX_DB.STAGING.STG_PSX_DATA;



CREATE OR REPLACE TABLE PSX_DB.DWH.DIM_DATE AS
WITH dates AS (
  SELECT DATEADD(day, seq4(), '2010-01-01') AS CAL_DATE
  FROM TABLE(GENERATOR(ROWCOUNT => 6000))
)
SELECT
    CAL_DATE AS DATE_KEY,
    YEAR(CAL_DATE) AS YEAR,
    MONTH(CAL_DATE) AS MONTH,
    DAY(CAL_DATE) AS DAY,
    DAYOFWEEK(CAL_DATE) AS DAY_OF_WEEK,
    MONTHNAME(CAL_DATE) AS MONTH_NAME,
    WEEKOFYEAR(CAL_DATE) AS WEEK_NO
FROM dates
WHERE CAL_DATE <= CURRENT_DATE();

CREATE OR REPLACE TABLE PSX_DB.DWH.FACT_STOCK_PRICES AS
SELECT
    s.STOCK_SYMBOL,
    d.DATE_KEY,
    t.OPEN_PRICE,
    t.HIGH_PRICE,
    t.LOW_PRICE,
    t.CLOSE_PRICE
FROM PSX_DB.STAGING.STG_PSX_DATA t
JOIN PSX_DB.DWH.DIM_STOCK s
    ON t.STOCK_SYMBOL = s.STOCK_SYMBOL
JOIN PSX_DB.DWH.DIM_DATE d
    ON t.TRADE_DATE = d.DATE_KEY;


CREATE OR REPLACE TABLE PSX_DB.DWH.FACT_MARKET_SUMMARY AS
SELECT
    STOCK_SYMBOL,
    YEAR(TRADE_DATE) AS YEAR,
    MONTH(TRADE_DATE) AS MONTH,
    AVG(CLOSE_PRICE) AS AVG_CLOSE,
    MAX(CLOSE_PRICE) AS MAX_CLOSE,
    MIN(CLOSE_PRICE) AS MIN_CLOSE,
    SUM(HIGH_PRICE - LOW_PRICE) AS PRICE_VOLATILITY
FROM PSX_DB.STAGING.STG_PSX_DATA
GROUP BY 1,2,3;

SHOW TABLES IN SCHEMA PSX_DB.DWH;


SELECT * FROM PSX_DB.DWH.FACT_STOCK_PRICES LIMIT 10;

SELECT * FROM PSX_DB.DWH.FACT_MARKET_SUMMARY LIMIT 10;

SELECT * FROM PSX_DB.DWH.DIM_STOCK LIMIT 10;

SELECT * FROM PSX_DB.DWH.DIM_DATE LIMIT 10;

